### ISSUE TITLE
ERC20 ERC721, 통합

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#44]

**Comment by atoye1** [comment]
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import '@openzeppelin/contracts/token/ERC721/ERC721.sol';
import '@openzeppelin/contracts/utils/Counters.sol';
import '@openzeppelin/contracts/access/Ownable.sol';
import '@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol';
import '@openzeppelin/contracts/token/ERC20/IERC20.sol';
import '@openzeppelin/contracts/utils/Strings.sol';

// import './EWEToken.sol';

interface ERC20Interface {
  function totalSupply() external view returns (uint256);

  function balanceOf(address account) external view returns (uint256);

  function transfer(address recipient, uint256 amount) external returns (bool);

  function approve(address spender, uint256 amount) external returns (bool);

  function allowance(address owner, address spender)
    external
    view
    returns (uint256);

  function transferFrom(
    address spender,
    address recipient,
    uint256 amount
  ) external returns (bool);

  event Transfer(address indexed from, address indexed to, uint256 amount);
  event Transfer(
    address indexed spender,
    address indexed from,
    address indexed to,
    uint256 amount
  );
  event Approval(
    address indexed owner,
    address indexed spender,
    uint256 oldAmount,
    uint256 amount
  );
}

contract EWEToken is ERC20Interface {
  mapping(address => uint256) private _balances;
  mapping(address => mapping(address => uint256)) public _allowances;

  uint256 public _totalSupply;
  string public _name;
  string public _symbol;
  uint8 public _decimals;
  uint256 private E18 = 1000000000000000000;

  constructor(string memory getName, string memory getSymbol) {
    _name = getName;
    _symbol = getSymbol;
    _decimals = 18;
    _totalSupply = 100000000 * E18;
    _balances[msg.sender] = _totalSupply; // 추가
  }

  function name() public view returns (string memory) {
    return _name;
  }

  function symbol() public view returns (string memory) {
    return _symbol;
  }

  function decimals() public view returns (uint8) {
    return _decimals;
  }

  function totalSupply() external view virtual override returns (uint256) {
    return _totalSupply;
  }

  function balanceOf(address account)
    external
    view
    virtual
    override
    returns (uint256)
  {
    return _balances[account];
  }

  function transfer(address recipient, uint256 amount)
    public
    virtual
    override
    returns (bool)
  {
    _transfer(msg.sender, recipient, amount);
    emit Transfer(msg.sender, recipient, amount);
    return true;
  }

  function allowance(address owner, address spender)
    external
    view
    override
    returns (uint256)
  {
    return _allowances[owner][spender];
  }

  function approve(address spender, uint256 amount)
    external
    virtual
    override
    returns (bool)
  {
    uint256 currentAllowance = _allowances[msg.sender][spender];
    require(
      _balances[msg.sender] >= amount,
      'ERC20: The amount to be transferred exceeds the amount of tokens held by the owner.'
    );
    _approve(msg.sender, spender, currentAllowance, amount);
    return true;
  }

  function transferFrom(
    address sender,
    address recipient,
    uint256 amount
  ) external virtual override returns (bool) {
    _transfer(sender, recipient, amount);
    emit Transfer(msg.sender, sender, recipient, amount);
    uint256 currentAllowance = _allowances[sender][msg.sender];
    require(
      currentAllowance >= amount,
      'ERC20: transfer amount exceeds allowance'
    );
    _approve(sender, msg.sender, currentAllowance, currentAllowance - amount);
    return true;
  }

  function _transfer(
    address sender,
    address recipient,
    uint256 amount
  ) internal virtual {
    require(sender != address(0), 'ERC20: transfer from the zero address');
    require(recipient != address(0), 'ERC20: transfer to the zero address');
    uint256 senderBalance = _balances[sender];
    require(senderBalance >= amount, 'ERC20: transfer amount exceeds balance');
    _balances[sender] = senderBalance - amount;
    _balances[recipient] += amount;
  }

  function _approve(
    address owner,
    address spender,
    uint256 currentAmount,
    uint256 amount
  ) internal virtual {
    require(owner != address(0), 'ERC20: approve from the zero address');
    require(spender != address(0), 'ERC20: approve to the zero address');
    _allowances[owner][spender] = amount;
    emit Approval(owner, spender, currentAmount, amount);
  }
}

contract EWENFT is ERC721URIStorage, Ownable {
  using Counters for Counters.Counter;
  Counters.Counter private _tokenIds;
  string public baseTokenURI;
  EWEToken public token;
  uint256 public nftPrice;

  constructor() ERC721('EWENFT', 'EWENFT') {
    nftPrice = 1;
    baseTokenURI = 'https://ewe-metadata.s3.ap-northeast-2.amazonaws.com/';
  }

  function connectionTestWithTransfer(address recipient, uint256 amount)
    public
    returns (bool)
  {
    token.transfer(recipient, amount);
    return true;
  }

  function mintNFT(address recipient) public onlyOwner returns (uint256) {
    require(token.balanceOf(recipient) > nftPrice);
    token.transferFrom(recipient, msg.sender, nftPrice);
    // uint256 currentAllowance = _allowances[sender][msg.sender];
    // token.transfer(recipient,  nftPrice);

    _tokenIds.increment();
    uint256 newItemId = _tokenIds.current();
    string memory tokenURI = string.concat(
      baseTokenURI,
      Strings.toString(newItemId),
      '.json'
    );
    _mint(recipient, newItemId);
    _setTokenURI(newItemId, tokenURI);

    return newItemId;
  }

  function getPrice() public view returns (uint256) {
    return nftPrice;
  }

  function getToken() public view returns (EWEToken) {
    return token;
  }

  function setToken(address tokenAddress) public onlyOwner returns (bool) {
    require(tokenAddress != address(0x0), 'Invalid tokenAddress');
    token = EWEToken(tokenAddress);
    return true;
  }
}

```

**Comment by atoye1** [comment]
테스트코드

```javascript
/* eslint-disable no-underscore-dangle */
/* eslint-disable no-undef */
const truffleAssert = require('truffle-assertions');

const EWEToken = artifacts.require('EWEToken');
const EWENFT = artifacts.require('EWENFT');
let token;
let nft;
let tokenAddr;

contract('EWENFT', (accounts) => {
  const name = 'EWEToken';
  const symbol = 'EWE';
  const decimals = 18;
  const totalSupply = '100000000000000000000000000';

  beforeEach(async () => {
    token = await EWEToken.new(name, symbol, {
      from: accounts[0],
    });
    tokenAddr = token.address;
    console.log(token.address);
    nft = await EWENFT.new({ from: accounts[0] });
    await nft.setToken(tokenAddr, { from: accounts[0] });
  });

  it('should set token propery', async () => {
    // await nft.setToken(tokenAddr, { from: accounts[0] });
    const erc20 = await nft.getToken({ from: accounts[0] });
    assert.strictEqual(erc20, tokenAddr);
  });

  it('should not be able to mint to accounts[0] itself', async () => {
    // await nft.setToken(tokenAddr, { from: accounts[0] });
    const erc20 = await nft.getToken({ from: accounts[0] });
    assert.strictEqual(erc20, tokenAddr);

    await truffleAssert.fails(nft.mintNFT(accounts[0], { from: accounts[0] }));
  });

  it('should fail to mint without setting allowance', async () => {
    await truffleAssert.fails(nft.mintNFT(accounts[1], { from: accounts[0] }));
  });

  it('should be able to mint after setting valid allowance', async () => {
    await nft.setToken(tokenAddr, { from: accounts[0] });
    console.log(await nft.getToken({ from: accounts[0] }));
    console.log(await nft.getPrice({ from: accounts[0] }));

    const amount = 10000000000000;
    const beforeBalance1 = await token.balanceOf(accounts[1]);
    assert.strictEqual('0', beforeBalance1.toString());
    await token.transfer(accounts[1], amount, { from: accounts[0] });
    const afterBalance1 = await token.balanceOf(accounts[1]);
    assert.strictEqual(amount.toString(), afterBalance1.toString());

    const allowanceValBefore = await token.allowance(accounts[1], accounts[0]);
    assert.strictEqual('0', allowanceValBefore.toString());

    await token.approve(accounts[0], amount, { from: accounts[1] });
    const allowanceVal = await token.allowance(accounts[1], accounts[0]);
    assert.strictEqual(amount.toString(), allowanceVal.toString());

    console.log(allowanceVal.toString());

    await truffleAssert.passes(nft.mintNFT(accounts[1], { from: accounts[0] }));
  });
});

```

**Comment by atoye1** [comment]
에러메시지
```bash
❯ truffle test test/EWENFT.test.js
Using network 'test'.


Compiling your contracts...
===========================
> Compiling ./contracts/Both.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/token/ERC721/ERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol
> Compiling @openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/Context.sol
> Compiling @openzeppelin/contracts/utils/Counters.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
> Compiling @openzeppelin/contracts/utils/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/utils/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/utils/math/Math.sol
> Artifacts written to /var/folders/mr/3m0tp4215cqg9hr952d47h8c0000gn/T/test--94393-bfADH6aDB9iO
> Compiled successfully using:
   - solc: 0.8.17+commit.8df45f5f.Emscripten.clang


  Contract: EWENFT
0x345cA3e014Aaf5dcA488057592ee47305D9B3e10
    ✔ should set token propery
0x9FBDa871d559710256a2502A2517b794B482Db40
    ✔ should not be able to mint to accounts[0] itself (236ms)
0xFB88dE099e13c3ED21F80a7a1E49f8CAEcF10df6
    ✔ should fail to mint without setting allowance
0x75c35C980C0d37ef46DF04d31A140b65503c0eEd
0x75c35C980C0d37ef46DF04d31A140b65503c0eEd
BN { negative: 0, words: [ 1, <1 empty item> ], length: 1, red: null }
10000000000000
    1) should be able to mint after setting valid allowance

    Events emitted during test:
    ---------------------------

    Ownable.OwnershipTransferred(
      previousOwner: <indexed> 0x0000000000000000000000000000000000000000 (type: address),
      newOwner: <indexed> 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 (type: address)
    )

    ERC20Interface.Transfer(
      from: <indexed> 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 (type: address),
      to: <indexed> 0xf17f52151EbEF6C7334FAD080c5704D77216b732 (type: address),
      amount: 10000000000000 (type: uint256)
    )

    ERC20Interface.Approval(
      owner: <indexed> 0xf17f52151EbEF6C7334FAD080c5704D77216b732 (type: address),
      spender: <indexed> 0x627306090abaB3A6e1400e9345bC60c78a8BEf57 (type: address),
      oldAmount: 0 (type: uint256),
      amount: 10000000000000 (type: uint256)
    )


    ---------------------------


  3 passing (1s)
  1 failing

  1) Contract: EWENFT
       should be able to mint after setting valid allowance:
     AssertionError: Failed with Error: Returned error: VM Exception while processing transaction: revert ERC20: transfer amount exceeds allowance -- Reason given: ERC20: transfer amount exceeds allowance.
      at passes (node_modules/truffle-assertions/index.js:142:11)
      at Context.<anonymous> (test/EWENFT.test.js:65:5)

```
